### ISSUE TITLE
[Feature] Docker infrastructure 

### ISSUE THREAD

**Issue by AntoniaSophia** [CarND-Capstone-Defender/car-nd-capstone#2]
I would like to push the Docker adaptations I've made in order to build and run a docker container with capstone project. I'm using Docker 17.09 on Ubuntu 16.04.
I will create a feature branch feature/docker-environment

**Comment by peterbarry** [comment]
Hi Antonia, No problem from my side. Do I need to do anything, you should have rights to also create repos now.

**Comment by peterbarry** [comment]
Merged.

**Comment by peterbarry** [comment]
completed
