### ISSUE TITLE
Generate the partial waypoint updater

### ISSUE THREAD

**Issue by peterbarry** [CarND-Capstone-Defender/car-nd-capstone#6]
Generate the initial waypoint updater as discussed in slack.

**Comment by ahmedzikry0** [comment]
Changes are done in "Feature waypoint partial" branch.
Now Final-way points msg is published with 200 points.
Also To make car move in a straight line with fixed throttle values, it is needed to do:
1- Open /home/user/original/ros/src/twist_controller/dbw_node.py
2- Uncomment lines in loop() which create throttle msg and publish it lines(77:81) 
3- run roslaunch launch/styx.launch 
4- Run Simulator
5- Change to Auto mode by un-checking Manual mark on the top left of the Simulator

**Comment by peterbarry** [comment]
Thanks - I'll verified messages are generated, and car moves when uncommeting the lines in dbw_node. py/. Verified that the twist commands look appropriate.



    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1153.21
          y: 1185.15
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.03281415219
          w: 0.999461470701
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1154.1
          y: 1185.21
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0317165628514
          w: 0.999496903267
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1155.42
          y: 1185.29
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0306816503695
          w: 0.999529207342
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1156.3
          y: 1185.34
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0295074886529
          w: 0.999564559252
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1156.74
          y: 1185.37
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0295769224392
          w: 0.99956250713
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1157.62
          y: 1185.42
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0294383164108
          w: 0.999566598845
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1158.94
          y: 1185.5
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0288908650751
          w: 0.999582571834
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1159.83
          y: 1185.55
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0295074886529
          w: 0.999564559252
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1160.27
          y: 1185.58
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0288857184989
          w: 0.999582720572
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1161.15
          y: 1185.63
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.027849061261
          w: 0.999612139676
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1162.47
          y: 1185.7
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0272358980072
          w: 0.999629034122
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1163.35
          y: 1185.74
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0260515891696
          w: 0.999660599755
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1164.23
          y: 1185.79
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0261208551601
          w: 0.999658792251
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      pose: 
        position: 
          x: 1165.56
          y: 1185.86
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0260595277185
          w: 0.999660392841
    twist: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      twist: 
        linear: 
          x: 11.1111111111
          y: 0.0
          z: 0.0
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
  - 
    pose:
